#!/usr/bin/env bash

set -eo pipefail

source .env

function build() {
	VITE_API_URL=$PROD_VITE_API_URL NODE_ENV=production pnpm build
}

function deploy() {
	npx wrangler pages deploy dist/
}

function main() {
	build && deploy
}

main "$@"
