version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - 5001:5001
    volumes:
      - ./server:/server
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
