name: CD
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Docker Build
        run: docker build -t combinator:latest .
      - name: Docker Export
        run: docker save -o combinator.tar combinator:latest
      - name: SSH Setup
        env:
          SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
      - name: Copy container to server
        run: |
          scp combinator.tar server:/tmp/combinator.tar
      - name: Load container
        run: |
          ssh server << 'ENDSSH'
          docker load -i /tmp/combinator.tar
          cd combinator
          git pull
          docker compose up -d
          rm /tmp/combinator.tar
          ENDSSH
          
